version: 0.2
            
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
        - cd Interface
        - npm i
        - npm i -g @angular/cli
  build:
    commands:
      - ng b --prod