version: 0.2
            
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
        - pwd
        - ls
        - npm i -g @angular/cli
  build:
    commands:
      - cd Interface
      - pwd
      - ls
      - ng b --prod
      - pwd
      - ls
      - cd dist
      - pwd
      - ls
      - cd Portfolio
      - pwd
      - ls