version: 0.2
            
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing node 12 and angular"
      - npm i -g @angular/cli
      - npm i @angular-devkit/build-angular
      - npm i @angular/compiler-cli
      - npm i @angular/compiler
  build:
    commands:
      - cd Interface
      - ng b --prod