version: 0.2
            
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
        - npm i @angular-devkit/build-angular
        - npm i @angular/compiler-cli
        - npm i @angular/compiler
        - npm i @angular/core
        - npm i -g @angular/cli
  build:
    commands:
      - cd Interface
      - ng b --prod