version: 0.2
            
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
        - npm i
        - npm i -g @angular/cli
  build:
    commands:
      - cd Interface
      - npm i
      - ng b --prod
artifacts:
  files:
      - '**/*'
cache:
  paths:
    - '/node_modules'
    - '/Interface/node_modules'