version: 0.2
            
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
        - pwd
        - npm i -g @angular/cli
  build:
    commands:
      - cd Interface
      - ng b --prod
      - pwd