version: 0.2
            
phases:
  install:
    runtime-versions:
      nodejs: 12.8.1
    commands:
      - echo "Installing node 12.8.1"
  build:
    commands:
      - cd Interface
      - ng b --prod